// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy3PssBFb8_yybh9RsqlhmnNDY_GC69Fs',
    appId: '1:1062686044316:web:c6d1c3a11de7e53e103d59',
    messagingSenderId: '1062686044316',
    projectId: 'car-rental-app-7524d',
    authDomain: 'car-rental-app-7524d.firebaseapp.com',
    storageBucket: 'car-rental-app-7524d.firebasestorage.app',
    measurementId: 'G-J9QLQ41XH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKcmKTKTtUGJSY-u20Af_0vzgwiaEQOZ4',
    appId: '1:1062686044316:android:ea5589ab0d6f21e4103d59',
    messagingSenderId: '1062686044316',
    projectId: 'car-rental-app-7524d',
    storageBucket: 'car-rental-app-7524d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAprYMoanjj9AiGclm6kv437-QNJ1uepNg',
    appId: '1:1062686044316:ios:4f19eaf4ca66442b103d59',
    messagingSenderId: '1062686044316',
    projectId: 'car-rental-app-7524d',
    storageBucket: 'car-rental-app-7524d.firebasestorage.app',
    iosClientId: '1062686044316-k66jsrigul0ocpcdfmu9ap4u5t65d5g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAprYMoanjj9AiGclm6kv437-QNJ1uepNg',
    appId: '1:1062686044316:ios:4f19eaf4ca66442b103d59',
    messagingSenderId: '1062686044316',
    projectId: 'car-rental-app-7524d',
    storageBucket: 'car-rental-app-7524d.firebasestorage.app',
    iosClientId: '1062686044316-k66jsrigul0ocpcdfmu9ap4u5t65d5g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy3PssBFb8_yybh9RsqlhmnNDY_GC69Fs',
    appId: '1:1062686044316:web:375d7126be8db587103d59',
    messagingSenderId: '1062686044316',
    projectId: 'car-rental-app-7524d',
    authDomain: 'car-rental-app-7524d.firebaseapp.com',
    storageBucket: 'car-rental-app-7524d.firebasestorage.app',
    measurementId: 'G-KSN2EMKD7F',
  );

}